### PR TITLE
feat(icon): add new link icon. closes #382

### LINKED ISSUE #382: "Permalink" icon
I would like a "permalink" icon included in our icon set... @gabrielhl Cay you help us on this?

Something like http://icon-park.com/imagefiles/link_icon_gray.png

### PR DESCRIPTION
**Pull request by xonic**
closes #382

### CODE REVIEW

**Comment by dami-gg** [comment]
Thanks for the icon and the extension of the readme file @xonic ;)

**Comment by dami-gg** [comment]
:+1:

**Comment by sambhav-gore** [comment]
👍

**Comment by rbarilani** [comment]
👍

**Comment by rbarilani** [comment]
@xonic can you remove the package-lock.json file?

**Comment by xonic** [comment]
done!

**Comment by rbarilani** [comment]
👍

**Comment by dami-gg** [comment]
:+1:

**Pull request merged**
