### PR TITLE
fix(accordion): remove triangle icon, use border hack instead

### LINKED ISSUE #277: Fix accordion triangle

### PR DESCRIPTION
**Pull request by xonic**
closes #277

### CODE REVIEW

**Comment by xonic** [comment]
@frontendherodk HALP! I don't get what's wrong with the travis checks.

**Comment by gregdeane** [comment]
@xonic The problem with the Travis build is that a ruby gem for scss linting needs to be installed.

`sudo gem install scss_lint`

**Comment by gregdeane** [comment]
@xonic as discussed in chat, this particular case isn't that the gem isn't installed. it appears that the tooltips file actually has linting errors.

https://travis-ci.org/zalando/dress-code/jobs/174741105#L1544

**Comment by rbarilani** [comment]
@gregdeane Good idea could be to migrate to pure node scss linter.... https://github.com/sasstools/sass-lint and get rid of ruby gems.... if you open an issue I can work on that... WDYT?

**Comment by gregdeane** [comment]
Thanks @rbarilani. Issue #283

**Comment by gabrielhl** [comment]
👍

**Comment by gabrielhl** [comment]
LGTM!

**Pull request merged**
