### PR TITLE
docs(search): make search work with basepath

### PR DESCRIPTION
**Pull request by sambhav-gore**
In live demo there is a basepath `dress-code` which was breaking the previous navigation logic for search.

This change replaces the last fragment of the url (after last '/') with the new path.

### CODE REVIEW

**Comment by sambhav-gore** [comment]
+1

**Comment by sambhav-gore** [comment]
👍

**Comment by rbarilani** [comment]
👍

**Comment by sambhav-gore** [comment]
👎

**Comment by sambhav-gore** [comment]
@rbarilani there was still an issue that it wasn't working from the very initial path which does not have any page. I have fixed the regex now and deployed the demo already. now this can be merged.

**Comment by sambhav-gore** [comment]
👍

**Comment by rbarilani** [comment]
👍

**Pull request merged**
