### PR TITLE
feat(icons): dc-icon--spin makes any icon rotate in-place

### LINKED ISSUE #350: Add icons for loading status
It would be so nice if the [icons](https://zalando.github.io/dress-code/03-atoms.html#icons) would include a loading-one as well (preferably with and without spinning), would this be possible?

### LINKED ISSUE #413: doc(icons): arrange icons by alphabetic order in the demo
doc(icons): arrange icons by alphabetic order in the demo

### PR DESCRIPTION
**Pull request by sambhav-gore**
Closes #350

Additionally I also alphabetically ordered icons in the demo. Closes #413

### CODE REVIEW

**Comment by rbarilani** [comment]
👍

**Comment by dami-gg** [comment]
The feature itself looks good to me but I still see the link icon broken...

image

**Comment by dami-gg** [comment]
:-1:

**Comment by sambhav-gore** [comment]
@dami-gg @rbarilani I have updated the gulp-iconfont version required. it does build correctly on travis as well.

**Comment by dami-gg** [comment]
@sambhav-gore if you change that then we also need to change the Node dependency version since for instance in my case I fulfill that requirement by having 6.2.2 but I can't do npm install because it triggers an incompatible module error on that library you changed

**Comment by sambhav-gore** [comment]
@dami-gg @rbarilani I have updated required node version to 7.0.0 now.

**Comment by dami-gg** [comment]
:+1:

**Comment by rbarilani** [comment]
👍

**Pull request merged**
