### PR TITLE
Topic/dialog fixes

### PR DESCRIPTION
**Pull request by dami-gg**
Adapted to follow a more logical markup where for instance the overlay is contained by the dialog and not viceversa.

### CODE REVIEW

**Comment by rbarilani** [comment]
@dami-gg Can you put a breaking change section into commit message ... If it's a breaking change.

Thoughts:
* Does It make sense to support the overlay outside of the dc-dialog block? @see ng-dialog
* Does it make sense to add dc--has-dialog or dc--has-dialog-open for body/html (for example to hide scroll bar)?

**Comment by dami-gg** [comment]
@rbarilani I'm rewriting the commit message to include the breaking change

Regarding your questions:

> - Does It make sense to support the overlay outside of the dc-dialog block? @see ng-dialog
I would say that if we want to add some kind of general overlay it should be a new component, since this is strictly linked (as we state with the class name) to the dialog.
  
> - Does it make sense to add dc--has-dialog or dc--has-dialog-open for body/html (for example to hide scroll bar)?
@gabrielhl may better give us an answer on this

**Comment by gabrielhl** [comment]
I agree that a more general dc-overlay might be useful in case someone wants to dim the screen for another reason, although I don't have any use cases in mind. In terms of the markup I think you guys have more knowledge than me since you're the ones doing implementation.

**Comment by rbarilani** [comment]
@dami do you think is possible to create a dc-overlay atom and use that atom in the dialog molecule.... (overlay stay outside) ? does it make sense?

**Comment by dami-gg** [comment]
@rbarilani yes I think it totally makes sense and it should work fine, I'll create an issue for that and work on it next week, since we need the dialog changes to be in the new release with the font-icon for our application and that's less urgent

**Pull request merged**
