### PR TITLE
fix(input): search input to have box-sizing of border-box

### LINKED ISSUE #286: in normalize.scss input[type="search"] has box-sizing of content-box which creates an issue when trying to place a search field on a page
In normalize.scss, input[type="search"] has box-sizing of `content-box`

This creates an issue if trying to place a search field within a table a cell. 

This is a minor issue but it would be best if we default it to `border-box` and use `content-box` only within `dc` styles.

### PR DESCRIPTION
**Pull request by sambhav-gore**
Closes #286

### CODE REVIEW

**Comment by sambhav-gore** [comment]
@rbarilani @dami-gg I do not see any changes to input search when content-box sizing is added. In other words, I found that we do not need to have content-box sizing at all. DO you know or remember why it was set as content-box at all?

Further, see the following screenshots for difference this PR makes, Look at the Merchant (search name) input field:

#### Before changes of this PR (content-box):
If 100% width is applied to the search input, the input width goes beyond the container width:

screen shot 2017-08-23 at 17 08 45

#### After changes of this PR (border-box):
Input width is 100% remains within the container:

screen shot 2017-08-23 at 17 09 03

**Comment by dami-gg** [comment]
yes, border-box seems like a much better approach for this case in my opinion.

Furthermore, see the comment that was there which looks like someone left a TODO for that:
// 2. Address `box-sizing` set to `border-box` in Safari and Chrome.

However, if that's a TODO, shall we do anything regarding the other comment @sambhav-gore ?
// 1. Address `appearance` set to `searchfield` in Safari and Chrome.

**Comment by rbarilani** [comment]
@dami-gg @sambhav-gore That is coming from normalize version ~3 ... in the next versions of normalize that got removed, so, IHMO we should remove it too and maybe think about a different strategy to include normalize in another issue.

**Comment by sambhav-gore** [comment]
@rbarilani @dami-gg I agree to have better strategy for including normalize in a different issue.

**Comment by rbarilani** [comment]
👍

**Comment by rbarilani** [comment]
@sambhav-gore Can you open that issue?

**Comment by rbarilani** [comment]
👍

**Comment by rbarilani** [comment]
@dami-gg ping

**Comment by dami-gg** [comment]
:+1:

**Pull request merged**
