### PR TITLE
fix(table): fix possible overlapping of sorters

### LINKED ISSUE #348: Make some space for sorting arrows.
Sometimes, table header with sorting arrows looks broken. See 
bug2
 
The fix is simple like
```css
.dc-table__th--sortable {
    padding-right: 20px;
}
```
Also, I don't think someone would need a multiline header, especially with sorting (it looks bad).
bug3

I would suggest to disable it.
```css
.dc-table__th {
    white-space: nowrap;
}
```

### PR DESCRIPTION
**Pull request by dami-gg**
Fixes #348

### CODE REVIEW

**Comment by rbarilani** [comment]
@dami-gg didi you also check how it works on "mobile"?

**Comment by dami-gg** [comment]
@rbarilani Good point. I've just realised it was already broken for mobile on master so perhaps we need a bigger issue for it:

image

**Comment by dami-gg** [comment]
:-1:

**Comment by rbarilani** [comment]
@dami-gg can we hide the sorter on mobile view?

**Comment by dami-gg** [comment]
The main problem is that the normal table design we have for mobile is way different to the desktop one and I do not see any way to make it sortable. Perhaps we would need input from a UX person.

I've checked bootstrap and foundation and they do not provide sortable tables, and furthermore I could not find that many examples which looked good on mobile.

This example simply hides the columns which do not fit 
 odhttps://datatables.net/extensions/rowreorder/examples/initialisation/responsive.html

We could do something like that maybe...

**Comment by rbarilani** [comment]
@dami-gg 👍 for hiding

**Comment by LeoAref** [comment]
@rbarilani I fixed it by overriding the default table style

**Comment by dami-gg** [comment]
If we show a desktop-like table hiding the columns the design will not be consistent.

Either we add a note saying that the tables cannot be sorted on mobile devices, which would be the case adding the class dc-table--responsive to the table, or we end up providing two different designs for tables depending on them being sortable or not...

I vote for the former. What's your take on that? @rbarilani @LeoAref

**Comment by rbarilani** [comment]
👍 for the first

**Comment by rbarilani** [comment]
@dami-gg I would have a look tomorrow

**Comment by rbarilani** [comment]
👍

**Comment by dami-gg** [comment]
:+1:

**Pull request merged**
