### PR TITLE
feat(messages): Align colors of messages and toasts

### LINKED ISSUE #250: Opacity of messages
Currently the messages have different opacities:
`info`, `warning` and `error`: 0.5
`succes` 0.95

Is there are reason to use opacity there at all?
For example the toasts do not use it.

The problem is that we show messages over other content and with `success` everything is fine but with the other classes the message is really bad to read caus of the opacity. 

And I do not know a way how to override just the opacity of the element, for example the `dc-msg--warning` looks like:
```css
.dc-msg--warning {
    border-color: #ebc600;
    background: rgba(255, 240, 158, 0.5);
    color: #99840e;
}
```
Is there a way to overwrite just the alpha property for this class?

Best

### PR DESCRIPTION
**Pull request by gabrielhl**
Close #250.

### CODE REVIEW

**Comment by gabrielhl** [comment]
@xonic

**Comment by xonic** [comment]
@gabrielhl do you think it makes sense have toast height 44px, same as SC header?

**Comment by gabrielhl** [comment]
@xonic Could be but let's not lose focus. This PR is for the colors only, let's investigate this height thing some other time.

**Comment by xonic** [comment]
👍

**Comment by rbarilani** [comment]
👍

**Pull request merged**
