### PR TITLE
feat(select-error-state): #236 add error state to select

### PR DESCRIPTION
**Pull request by ashwinaggarwal**
**dc-select--is-error** class to show error implemented as below.

screen shot 2016-08-15 at 17 57 56

### CODE REVIEW

**Comment by gabrielhl** [comment]
👍

**Comment by sambhav-gore** [comment]
:+1:

**Comment by gregdeane** [comment]
@ashwinaggarwal please update this branch with the `develop` branch and fix any potential merge conflicts.

**Comment by ashwinaggarwal** [comment]
@gregdeane updated the branch by merging develop to it

**Comment by gabrielhl** [comment]
LGTM!

**Comment by gabrielhl** [comment]
👍

**Pull request merged**
