### PR TITLE
feat(icons): Add bar-chart, line-chart, pointer icons

### PR DESCRIPTION
**Pull request by ashwinaggarwal**
Hi guys,

We need some additional icons in the dresscode. I didn't know how to name the icons, so the icon names are how we suppose to use them in our code. Following icons have been added
- [x] bar-chart
- [x] line-chart
- [x] pointer

screen shot 2017-06-30 at 14 14 26

And below is how we intend to use them

screen shot 2017-06-30 at 14 15 11

Please review and suggest if changes are needed. 

Best,
Ashwin

### CODE REVIEW

**Comment by frontendherodk** [comment]
@peter-lowe please have a look as well

**Comment by xonic** [comment]
👍

**Comment by rbarilani** [comment]
👍

**Comment by xonic** [comment]
👍

**Comment by xonic** [comment]
👍

**Pull request merged**
