### PR TITLE
fix(dialog): Fix padding of button zone

### LINKED ISSUE #217: Padding in dialog action area is unequal
Since the space below buttons was removed, the visual padding below the button in dc-dialog is now too small and should be adjusted.

image

### PR DESCRIPTION
**Pull request by gabrielhl**
Close #217

### CODE REVIEW

**Comment by sambhav-gore** [comment]
:+1:

**Comment by gregdeane** [comment]
@sambhav-gore @gabrielhl This lack of space was compensated for in Solution Center so please keep that in mind when merging this change. Solution Center will have too much space after this change.

**Comment by gregdeane** [comment]
👍

**Comment by gabrielhl** [comment]
@gregdeane actually, looks broken on SC: 
image

**Comment by gregdeane** [comment]
@gabrielhl The changes were made some time ago but I just checked and they aren't yet on Stage or Prod.

Check Integration and you'll see the update.

**Pull request merged**
