### PR TITLE
Topic/377 quick search in docs

### PR DESCRIPTION
**Pull request by sambhav-gore**
@rbarilani and @dami-gg, when you get time please see this. I implemented it slight differently than originally thought about. This is now a quick search (meaning it doesn't search for detailed text or every css class, but searches through indexed headers and sub headers).
Let me know what do you think of this.

### CODE REVIEW

**Comment by dami-gg** [comment]
I like the functionality but I think we should display it in another place on the demo page. Perhaps in the sidebar menu?

Especially on mobile it looks broken:

image

Moreover, I like to be able to search per sections, but it feels a bit weird as a user to for instance Search "Forms - Text Input" and be shown a page which hides exactly that title and shows only the content after it. Do you see any way of improving that @sambhav-gore?

Finally, if you don't mind, could you please squash your commits into a single one towards a cleaner changelog?

**Comment by sambhav-gore** [comment]
@dami-gg I have pushed the changes as per your comments.

**Comment by dami-gg** [comment]
it does look great now @sambhav-gore !!! Thanks for changing it

I have just a nitpick but I don't know if it's possible to do it or not. Let me know your opinion about it:

When you're in mobile and search something it would be nice it the sidebar closes like it does when clicking a menu item on it. Do you think it's possible?

The rest looks quite well to me

**Comment by sambhav-gore** [comment]
@dami-gg I have implemented the sidebar auto closing as per your last comment.

**Comment by rbarilani** [comment]
👍

**Comment by sambhav-gore** [comment]
👍

**Pull request merged**
