### PR TITLE
chore(release): 2.0.0

### LINKED ISSUE #318: Release dress code
Are there breaking changes? Also, ensure that it's installed in SC to test that it's working.

### PR DESCRIPTION
**Pull request by dami-gg**
Closes #318

### CODE REVIEW

**Comment by dami-gg** [comment]
:+1:

**Comment by gregdeane** [comment]
@dami-gg How did this look in SC? Any oddities or code changes to SC that were necessary? I think there should be at least some breaking changes in SC with the removal of the deprecated code.

**Comment by dami-gg** [comment]
Everything besides the icons looked fine and that's due to the way we prepare the build, we should copy them from /dist but still showed up as squares.

Anyway it's not a problem of Dress Code how applications use it and we won't update to that version in the current production code of Solution Center so we're safe there.

To prove that the icons are working I've also integrated that in the navigation and they show up well so everything is ready for the release as soon as any of you guys approve it too :)

**Comment by cjhowald** [comment]
👍

**Comment by dami-gg** [comment]
:+1:

**Pull request merged**
