### PR TITLE
feat(divider): add secondary divider

### LINKED ISSUE #310: Add a secondary divider
Add a secondary divider in with `$dc-gray70` / `#ededed` color

### PR DESCRIPTION
**Pull request by LeoAref**
screen shot 2017-01-16 at 11 23 24

Closes #310

### CODE REVIEW

**Comment by LeoAref** [comment]
@gabrielhl @gregdeane

**Comment by gregdeane** [comment]
@LeoAref Looks good man. Thx!

**Comment by gregdeane** [comment]
👍

**Comment by gabrielhl** [comment]
The demo is also quite clever!

**Comment by gabrielhl** [comment]
👍

**Comment by gregdeane** [comment]
👍

**Comment by dami-gg** [comment]
:+1:

**Comment by cjhowald** [comment]
👍

**Comment by LeoAref** [comment]
@rbarilani ☝️ (This PR misses 1 approvals from group technical (0/1).)

**Comment by rbarilani** [comment]
👍

**Comment by gabrielhl** [comment]
It seems something is wrong with the zappr group setting?

**Comment by gregdeane** [comment]
@gabrielhl It appears so. We'll prioritize and get to it soon.

**Comment by gregdeane** [comment]
@LeoAref We had to update the zappr config... would you mind merging `develop` into this PR so we can merge it? Thx!

**Comment by LeoAref** [comment]
@gregdeane Done

**Comment by gregdeane** [comment]
👍

**Comment by gabrielhl** [comment]
👍

**Comment by dami-gg** [comment]
:+1:

**Pull request merged**
