### PR TITLE
Feature/185 regression tests

### PR DESCRIPTION
**Pull request by dami-gg**
Due to a problem to squash all commits after having merged from master I open this new PR and close the former #375 

I've addressed most of the missing aspects mentioned in that old PR's description, although the following still have to be implemented:

- [x] Document how the setup works for other developers
- [x] Extend it to also test molecules
- [x] Handle server termination upon unexpected errors
- [x] Load fonts
- [x] Check screenshots
- [x] Find a solution to store images outside of the repository
- [ ] Integrate test in Travis (just for releases) --> To be moved to a new issue
- [ ] Write code to take screenshots on hover or on click for certain elements (eg. tooltip, side-revealer...) --> This should be an independent feature to be considered

### CODE REVIEW

**Comment by dami-gg** [comment]
:-1:

**Comment by dami-gg** [comment]
Besides the documentation which I will write tomorrow, there's a problem with the font icons which are not actually loaded and hence not seen in the screenshots.

I believe the solution is to serve them via Express but I have to figure out how. I hope I will be able to fix that tomorrow as well.

For the rest, it's all set up and open for review and suggestions from your side @rbarilani @sambhav-gore Let me know your thoughts ;)

**Comment by dami-gg** [comment]
:-1:

**Comment by dami-gg** [comment]
This looks like a nice option for the baseline storage:

https://git-lfs.github.com/

**Comment by dami-gg** [comment]
:+1:

**Comment by rbarilani** [comment]
👍

**Pull request merged**
