### PR TITLE
feat(select): Add disabled and match height with other atoms.

### LINKED ISSUE #187: Select doesn't align with buttons
Currently the `<select>` element is 32px high and doesn't align with buttons or fields. It should be 36px high and align with all other elements.

### LINKED ISSUE #189: Select atom has no disabled state
Add disabled state to `select` atom

### PR DESCRIPTION
**Pull request by gabrielhl**
- Add disabled state to select.
- Modify padding to add 4px to select's height, to match buttons and other basic atoms.

Close #187. Close #189.

### CODE REVIEW

**Comment by rbarilani** [comment]
@gabrielhl dc-select--disabled class doesn't exist.

My suggestion:
```scss
@mixin dc-select--disabled { // disabled style here }

@mixin dc-select-selectors {
   .dc-select {
     @include dc-select;
      &[disabled] { @include dc-select--disabled }
   }
}

**Comment by gabrielhl** [comment]
@rbarilani that was exactly how I did it first. But then I saw that the` dc-checkbox` and `dc-radio` are using `&[disabled]` with no specific mixin for disabled so I followed the same pattern. Also I forgot to remove the class from the demo, sorry. 
Should we change the pattern for everyone by using a separate mixin for the disabled?

**Comment by rbarilani** [comment]
@gabrielhl Yep... let's use the same more flexible patterns for the others? WDYT? Maybe let´s close this pull request just with ```dc-select```enhancement and then open another one for the refactor. WDYT?

**Comment by gabrielhl** [comment]
Yes and then we can really check the pattern for all states that could be improved not just disabled

**Comment by gabrielhl** [comment]
I fixed the demo class, can we merge this? DC hasn't seen any merge action in weeks 😄

**Pull request merged**
