### PR TITLE
Topic/304 update release scripts

### PR DESCRIPTION
**Pull request by gregdeane**
#304 
#293 

* To test this PR, make sure to remove ` && npm run push:release` from the `postrelease` script before running the `npm run release <VERSION>` script.
* After testing, you need to delete the created branch and revert the last commit.

### CODE REVIEW

**Comment by rbarilani** [comment]
@gregdeane The bump must be done before build.

**Comment by gregdeane** [comment]
@rbarilani The bump is happening before the build:

[Line 16](https://github.com/zalando/dress-code/blob/f4d066cc66b57288beb0dd626b1c2931186f3277/package.json#L16) bumps the version in `package.json`.
[Line 13](https://github.com/zalando/dress-code/blob/f4d066cc66b57288beb0dd626b1c2931186f3277/package.json#L13) is run immediately after the bump.
[Line 15](https://github.com/zalando/dress-code/blob/f4d066cc66b57288beb0dd626b1c2931186f3277/package.json#L15) starts the build.

**Comment by rbarilani** [comment]
@gregdeane All right... sorry I missed it!

**Comment by rbarilani** [comment]
👍

**Comment by gregdeane** [comment]
@rbarilani No problem man!

**Comment by gregdeane** [comment]
👍

**Comment by gregdeane** [comment]
@gabrielhl Please thumbs up.

**Comment by gabrielhl** [comment]
👍

**Comment by gregdeane** [comment]
👍

**Comment by gregdeane** [comment]
@cjhowald @dami-gg @frontendherodk Can one of you approve this please?

Also, maybe we can add @rbarilani and @sambhav-gore to the list of tech approvers so we can move PR's through more quickly?

**Comment by dami-gg** [comment]
:+1:

**Pull request merged**
