### PR TITLE
chore(bower): drop bower support

### LINKED ISSUE #346: chore(bower): drop bower support
Drop bower support.
Remove bower.json and update documentation where bower is mentioned.

### PR DESCRIPTION
**Pull request by rbarilani**
Drop bower support.

close #346

### CODE REVIEW

**Comment by rbarilani** [comment]
@dami-gg @frontendherodk ping for review

**Comment by rbarilani** [comment]
👍

**Comment by dami-gg** [comment]
Looks fine to me, just wondering whether we should add a temporal note to the readme saying that bower support has been discontinued after version 2.1.0

Although it may be enough with adding it to the release notes

**Comment by dami-gg** [comment]
:+1:

**Comment by rbarilani** [comment]
@dami-gg "...Although it may be enough with adding it to the release notes..." Yep!

**Pull request merged**
