### PR TITLE
feat(font-cache-busting): #203 add font cache busting by appending query string based on the package version

### LINKED ISSUE #203: Font files versions
We had issues with unmatching icons, when switching from one app (using dresscode ver.1.2) to another app (using dresscode ver.2.0). Font files has been cached by first app but it was incompatible in second app.

Probably postfixing the font files by a version name would be a good idea.

### PR DESCRIPTION
**Pull request by rbarilani**
* be sure that icons and css icon stylesheet is generated before compiling the styles
* remove gulp-iconfont-css because not maintained anymore
* sort generated css classes, mixins, etc. alphabetically
* updates RELEASING.md, bump must be done before run the build

Can close #203

### CODE REVIEW

**Comment by RyanVelasco** [comment]
uwhsus the bzbz hshzms kzskbdhd jßdhd htvhďhd hdhdvdjd haf hzvd jdje jsvd shczjs skdks zjsv zvjsdcdjs dddddn zndvhd sjs  shcddmd bdcx dzg d dhd dvdbs fhsysnd hshfvshd  hd f gdb ndvdbd hd d hd hd xjd sbbddhddhhd dbdvdd dj.

**Comment by RyanVelasco** [comment]
vhsdb zjvz su dbsg jzgzbd jdb d

**Comment by RyanVelasco** [comment]
hhzh zzkbz zhdvd dh

**Comment by rbarilani** [comment]
@mrac Can you check if this PR can solve the issue #203?

**Comment by sambhav-gore** [comment]
Confirmed this does not break anything and that cache busting is applied with passing query as the dress code version.

**Comment by sambhav-gore** [comment]
:+1:

**Pull request merged**
