### PR TITLE
Add information about variables for build

### PR DESCRIPTION
**Pull request by avb1989**
#388 Adds information about dc-font-path and dc-image-path variables

### CODE REVIEW

**Comment by rbarilani** [comment]
@avb1989 Hey, thanks for your contribution. Although we would like to see that information not in the readme but more likely [here](https://github.com/zalando/dress-code/tree/master/docs/demo/materials/01-core)... add a page `04-scss-reference.html` in that folder with the following content:

```html
---
notes: |
    Variables used in Dress Code Core and their default values
---

<table class="dc-table">
  <thead class="dc-table__thead">
    <tr class="dc-table__tr">
      <th class="dc-table__th">Variable</th>
      <th class="dc-table__th">Type</th>
      <th class="dc-table__th">Default</th>
      <th class="dc-table__th">Description</th>
    </tr>
  </thead>
  <tbody class="dc-table__tbody">
    <tr class="dc-table__tr">
      <td class="dc-table__td">$dc-font-path</td>
      <td class="dc-table__td">String</td>
      <td class="dc-table__td">"../fonts"</td>
      <td class="dc-table__td">Fonts folder</td>
    </tr>
    <tr class="dc-table__tr">
      <td class="dc-table__td">$dc-image-path</td>
      <td class="dc-table__td">String</td>
      <td class="dc-table__td">"../img"</td>
      <td class="dc-table__td">Images folder</td>
    </tr>
  </tbody>
</table>
```

To see a preview just run `npm start` and open your browser at `http://localhost:3000`

**Comment by rbarilani** [comment]
@avb1989 Any updates? We'd love to see your contribution merged.

**Comment by avb1989** [comment]
Hey, sorry for the late update.
Anyway, the reason I added it in the README was because was breaking my build.
Thus it seemed important enough to be on the 1st page. What do you think ?

Might be more friendly for newbies to not go through the entire docs until they have to.

**Comment by rbarilani** [comment]
@avb1989 I agree. I would like just to do some updates before merge, can you [allow changes](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)?

**Comment by avb1989** [comment]
Yes. It is already allowed.

**Comment by rbarilani** [comment]
@avb1989 Great! Will take care about this PR in the next days.. thanks a lot.

**Comment by rbarilani** [comment]
👍

**Comment by dami-gg** [comment]
:+1:

**Pull request merged**
