### PR TITLE
Add dc-select--small. Close #313

### LINKED ISSUE #313: Add small modifier to dc-select
Proposed new component modifier: dc-select--small
The height of 24px (2.4 rem) allows to align horizontally with other form items (checkbox, radio, switch)

image

### PR DESCRIPTION
**Pull request by gabrielhl**
Adds dc-select--small modifier and demo example.

Closes #313, #314

### CODE REVIEW

**Comment by gregdeane** [comment]
@gabrielhl We had to update the zappr config... would you mind merging `develop` into this PR so we can merge it? Thx!

**Comment by gabrielhl** [comment]
@gregdeane thanks for the heads up, doing it now

**Comment by gregdeane** [comment]
@gabrielhl Thanks man. @LeoAref 

Please note that we are prioritizing Dress Code PRs/release for next week. Thanks for the contributions!

**Comment by LeoAref** [comment]
@gregdeane I'm not sure that i got what you mean exactly, could you clarify?

**Comment by gregdeane** [comment]
@LeoAref I just wanted to let you guys know that your PRs and a Dress Code release is being prioritized by Team Norris for next week. In other words, you should see your PRs merged and a release next week.

**Comment by cjhowald** [comment]
In testing, looks like the check boxes and radio buttons actually have a height of 22px, so it does not line up:

image

I'll update the height to match.

**Comment by cjhowald** [comment]
According to @xonic the line height for the checkboxes and radio buttons should also be 24px. I'll update them them to match and leave the select as is.

**Comment by gabrielhl** [comment]
Thanks @cjhowald

**Comment by cjhowald** [comment]
After further discussion with @xonic, it appears there are other places in the dress code that expect a height of 22px. To avoid scope creep in this PR, we will instead set the height of the new select to 22px to be consistent and open a new issue to address the discrepancy everywhere.

**Comment by cjhowald** [comment]
👍

**Comment by gabrielhl** [comment]
Looks good to me. Thanks for your contribution @cjhowald

**Comment by gabrielhl** [comment]
👍

**Comment by gabrielhl** [comment]
👍

**Pull request merged**
