### PR TITLE
WIP - Setup visual regression testing

### PR DESCRIPTION
**Pull request by dami-gg**
**This is still a work in progress pull request. Not ready yet for merge**

I've pushed what I have managed to do this month's slot on this topic, namely:

- Setup PhantomCSS for visual regression tests
- Configure it according to our needs
- Write initial example tests for atoms and molecules
- Add common utils to avoid repetition on test specs
- Add example tests for modifiers and click actions on components

To be done on next month's cycle:

- [X] Solve the problem with demo's left menu overlapping tested components on screenshots on mobile size viewport.
  - I tried both clicks on the toggle and removal of the related class in the HTML element but couldn't make it work yet.
- [x] Try to centralize some more common functionality regarding the CasperJS tests execution skeleton to avoid repetition.
- [ ] Document how the setup works for other developers
- [x] Integrate --rebase option to NPM scripts to allow baseline images generation when a change is expected.
- [ ] Ask another collaborator to write a couple of tests to try to find possible areas for improvement on the current setup
- [ ] Rebase commits on a single one with nice wording

### CODE REVIEW

**Comment by dami-gg** [comment]
:-1:

**Comment by dami-gg** [comment]
I've made a big progress on this topic but I still have to finalise it in the next iteration. 

Current setup is:

 npm run test / yarn test triggers a runner (runner.js) script which forks two different processes which communicate with each other:
- An express server (server.js) which serves all the pages under docs/demo/materials/03-atoms
  - [ ] Need to extend it to also add molecules here
 - When up and running a CasperJS job is started to run all tests (suites.js) and take screenshots.
  - Suites are automated and we should be able to cover basic tests for all components
  - Tests depending on actions like clicks, hovering and so on will have to be investigated further.

Feel free to take a look and leave your opinions @rbarilani @sambhav-gore 

On the next iteration, I'll take care of doing some adjustments, document how to use it and squash all commits and hopefully finish this.

**Comment by dami-gg** [comment]
:-1:

**Comment by rbarilani** [comment]
👍 I think this is a great progress @dami-gg! awesome!

**Comment by dami-gg** [comment]
Closed in favor of #412

**Pull request closed without merging**
