### PR TITLE
feat(grid): Add utility classes to hide/show at different breakpoints

### LINKED ISSUE #287: Enhancement request: Add utility classes for responsive behaviour
It will be helpful if some helper utility classes (for responsiveness) are added, something as follows:

- hide-for-medium-up (hides the element for screen sizes 'medium width' and up)
- show-for-large-down (shows the element only for screen sizes of large width and below).

Something to keep in mind (WHEN possible) while writing the styles the default should always consider smallest possible screen sizes first (mobile-first-approach), the modifiers should only modify the behaviour for targeted screen-sizes and up.

### PR DESCRIPTION
**Pull request by gabrielhl**
Close #287

### CODE REVIEW

**Comment by sambhav-gore** [comment]
@gabrielhl I see some inconsistencies in the demo for this change with `show-for-xxx` classes.
If only class added to an element is `show-for-xxx` then it means it will never hide, so in the demo we should add all necessary classes so that it makes sense. 
Additionally, can you add a small description for the classes in the demo briefly describing the class names, such as:

>Use `dc-hide-from-[small|medium|large|huge]` to hide a target element on a specific breakpoint size

**Comment by rbarilani** [comment]
@gabrielhl what about something similar to this..... http://getbootstrap.com/css/#responsive-utilities

**Comment by gabrielhl** [comment]
@rbarilani @sambhav-gore Thanks for suggestions will work on this ASAP

**Comment by sambhav-gore** [comment]
:+1:

**Comment by gabrielhl** [comment]
We decided to keep a simpler approach, but improved the functionality -- dc-show-from-x now hides everything below it, which wasn't the case before.

**Comment by gabrielhl** [comment]
👍

**Pull request merged**
