### PR TITLE
refactor(svg-icons): align svg-icons naming with font icons naming

### PR DESCRIPTION
**Pull request by rbarilani**
BREAKING CHANGE: some svg-icons were renamed

	```info.svg -> info-circle.svg```
        ```msg-error.svg -> error.svg```
	```msg-info.svg -> info.svg```
	```msg-neutral.svg -> neutral.svg```
	```msg-success.svg -> success.svg```
	```msg-warning.svg -> warning.svg```

### CODE REVIEW

**Comment by gabrielhl** [comment]
The downside from this is that the msg- icons were kind of a family, and it's easy to know that those are the ones to use for messages

**Comment by rbarilani** [comment]
@gabrielhl Yep that's true but they can also be used outside the message component. Another reason for this change is to align font icons and dc-icon classes with the provided svg files. Check the 2.0.0 alpha section in the changelog.

**Comment by rbarilani** [comment]
@dami-gg any update on that one?

**Comment by dami-gg** [comment]
worked like charm You can merge it from my point of view

**Pull request merged**
