### PR TITLE
feat(side-revealer): add new molecule to give the ability to have main content and sub content in the side'

### LINKED ISSUE #258: Add side revealer
This is an example

### PR DESCRIPTION
**Pull request by LeoAref**
#### Demos:

side-revealer-demo-1 1

side-revealer-demo-2 1

-----

Closes #258

### CODE REVIEW

**Comment by gabrielhl** [comment]
Just tested this is super cool!

**Comment by gabrielhl** [comment]
👍

**Comment by rbarilani** [comment]
👍

**Comment by rbarilani** [comment]
@gregdeane Can you add me and @gabrielhl as collaborators?

**Comment by gregdeane** [comment]
@rbarilani You're already a collaborator with `write` perms via the team "brand-solutions."
@gabrielhl You're already a collaborator with `admin` perms.

**Comment by rbarilani** [comment]
@gregdeane Sorry greg zappr was not updating his status... so I thought that I was not in the collaborators... but now I see:

This pull request can be automatically merged by project collaborators
Only those with write access to this repository can merge pull requests.

**Comment by gregdeane** [comment]
@rbarilani Zappr approvers must be "public" on the Zalando group.

**Pull request merged**
