### PR TITLE
Add users icon; update help and user icon.

### LINKED ISSUE #319: Add users icon and update help and user icons
New versions of those icons plus a new one to access user management are needed by the new navigation

### PR DESCRIPTION
**Pull request by gabrielhl**
Closes #319

@dami-gg Here are the new/edited icons. The issue here is that if someone updates DC without updating to the new nav they will get the new user and help icons in the old nav.

### CODE REVIEW

**Comment by dami-gg** [comment]
I don't fully get what you mean, you just added a new icon called "users" not being used anywhere so far What's the problem with that?

**Comment by gregdeane** [comment]
@gabrielhl What is the issue number associated with this PR?

**Comment by dami-gg** [comment]
Ah ok I've got it now. Is it really problematic if those icons are replaced because of updating the library to this latest version? 

If that's the case we should maybe split this PR into two different ones, merge now only the "users" icon and release later a new version with the updated icons.

**Comment by dami-gg** [comment]
:+1:

**Comment by dami-gg** [comment]
:+1:

**Comment by gregdeane** [comment]
👍

**Comment by dami-gg** [comment]
:+1:

**Comment by gregdeane** [comment]
👍

**Comment by gregdeane** [comment]
👍

**Pull request merged**
