### PR TITLE
feat(tables): Add sortable header

### PR DESCRIPTION
**Pull request by gabrielhl**
@sambhav-gore @xonic Please check this out your input would be appreciated!

### CODE REVIEW

**Comment by sambhav-gore** [comment]
I see an extra border appearing occasionally:

screen shot 2016-09-07 at 18 06 40

This is showing up when I refresh the page (when page inspector is not open).

**Comment by gabrielhl** [comment]
Sorter arrows now look like the ones being used in production by some of our apps. This required me to udpate the SCSS and demo. It now works in a different way, you have to add an empty element inside of the th (or td, or whatever) that has the sorter class. 

image

**Comment by sambhav-gore** [comment]
@gabrielhl How is the interaction supposed to work here in this design. The user will click on the small ascending/descending icons to sort by that order? Or she will click on the entire header ? 

If it is former (clicking on small arrows), it will hard to implement as the descending icon is a pseudo element (:after element) where a developer will have hard time binding events from the small icons to do the change in sorting order for the data. 

If it is latter (clicking on entire header) rotates through sorting cycle ( none -> ascending -> descending -> none) then it will make sense to have pointer cursor for entire header and not to have pointer for the small icon.

**Comment by xonic** [comment]
Good comment! The whole header cell is clickable. 

----------------------------
Thomas Nägele
http://xon1c.com
@xon1c

Sonnenallee 92
12045, Berlin

+49 170 311 27 64
tom@naegele.it

**Comment by gabrielhl** [comment]
I'll update the cursor to be a pointer on the whole header.

**Comment by gabrielhl** [comment]
@xonic I did it! 💪

**Comment by xonic** [comment]
@gabrielhl great job man! I suppose the double sorting on the same table (asc/desc) is for demo purposes? Also, I'd give the `.dc-table__th--sortable .dc-table__sorter { margin-left: 8px; }` instead of 4px.

**Comment by xonic** [comment]
just to tease you a little more ;)

**Comment by sambhav-gore** [comment]
👍

**Pull request merged**
