### PR TITLE
feat(typography): Improve typography demo

### LINKED ISSUE #289: .dc-h3 has the wrong font-size in code
The `font-size` for `dc-h3` currently has a value of `1.8rem;`. This is wrong. It should be `2.2rem`, according to the demo and our mockups. Likely a copy-paste issue from `dc-h4`.

### LINKED ISSUE #291: Break typography section into several sub-files
To improve demo code readability

### PR DESCRIPTION
**Pull request by gabrielhl**
- Separate typography section into several sections for better demo code readability. Close #291 
- Fix incorrect sizing of dc-h3. Close #289

### CODE REVIEW

**Comment by gregdeane** [comment]
@gabrielhl Looks good. But can you open another issue for the "separate typography" changes and add the issue number to your initial comment?

**Comment by gabrielhl** [comment]
@gregdeane Like this?

**Comment by gregdeane** [comment]
@gabrielhl yep. thx!

**Comment by gregdeane** [comment]
👍

**Pull request merged**
