### PR TITLE
Topic/dress code grid

### PR DESCRIPTION
**Pull request by sambhav-gore**
This pull request can be reviewed now. I am working on adding comments to important parts of the code.

### CODE REVIEW

**Comment by sambhav-gore** [comment]
@dami-gg @cjhowald @gregdeane @rbarilani - This is how it looks: 
dc-grid-html

**Comment by rbarilani** [comment]
@sambhav-gore awesome... I have to tried it as soon as possible... I had a look at the code and it looks really good. Great job @sambhav-gore !

**Comment by gregdeane** [comment]
@sambhav-gore same here. haven't pulled the branch yet but amazing work! code looks excellent.

**Comment by sambhav-gore** [comment]
@rbarilani thanks. Will edit the commit messages.

**Comment by rbarilani** [comment]
@sambhav-gore @dami-gg For me this pull request cam be merged.... Let's aim for the beta milestone. WDYT?

**Comment by dami-gg** [comment]
Yes, let's merge it and then we implement it in the solution center to check that everything works fine before releasing the new version

**Pull request merged**
