### PR TITLE
fix(style): Standardise elements height to 2.4rem

### LINKED ISSUE #323: Height discrepancy for some inputs
Some of the dress code inputs have a height of 22px. They should be 24px instead.

- dc-select--small
- dc-checkbox (note: dc-checkbox--alt is already 24px line height)
- dc-radio
- dc-btn--small

Also check the following, which might need to change to match:
- dc-list__title

### PR DESCRIPTION
**Pull request by gabrielhl**
Close #323

### CODE REVIEW

**Comment by frontendherodk** [comment]
@gabrielhl in the issue you mention that you wanna keep the height of checkbox/radio etc. 22px but with the changes you made they're 24. Is that intended?

**Comment by gabrielhl** [comment]
@frontendherodk the height of the element is 24 but the height of the box or circle is 22. This is to keep the visual style intact for now, but allow an easier alignment of the elements.

**Comment by frontendherodk** [comment]
Ah. A little confusing from the issue description but all good then

**Comment by frontendherodk** [comment]
👍

**Comment by gabrielhl** [comment]
👍

**Pull request merged**
