### PR TITLE
feat(dc-label__sub): add dc-label__sub mixins and classes

### PR DESCRIPTION
**Pull request by rbarilani**
* Add dc-label__sub to replace dc-label--required to give the possibility to customize the wording and enable localization
* dc-label--required deprecated

### CODE REVIEW

**Comment by sambhav-gore** [comment]
@rbarilani Can you describe it as a breaking change in the commit message for the changelog ?

**Comment by rbarilani** [comment]
@sambhav-gore Well in theory is not a breaking change because I didn't remove ```dc-label--required``` mixin and class. I just added a deprecation and leave the maintainers deciding when we can safely remove ```dc-label--required``` .....

**Comment by sambhav-gore** [comment]
:+1:

**Comment by gabrielhl** [comment]
👍

**Pull request merged**
