### PR TITLE
feat(tables): Make table responsiveness optional

### PR DESCRIPTION
**Pull request by gabrielhl**
BREAKING CHANGE: Table responsive behavior is now optional.

- Make table responsiveness optional.
- Update and simplify demo.

### CODE REVIEW

**Comment by gabrielhl** [comment]
Please review @gregdeane @cjhowald @dami-gg

**Comment by sambhav-gore** [comment]
I pushed a commit to solve a minor issue here:
If the column name is big, then in responsive mode the label overlaps the contents, see screenshot below (second card, second row):

#### Before Fix:

screen shot 2017-02-09 at 15 04 08

#### After Fix:

screen shot 2017-02-09 at 15 28 04
(Added overflow hidden and text-overflow as ellipsis)

**Comment by gabrielhl** [comment]
Thanks @sambhav-gore

**Comment by gabrielhl** [comment]
👍

**Comment by sambhav-gore** [comment]
👍

**Pull request merged**
