### PR TITLE
refactor(dc-table): refactor dc-table, see #110, add $dc-image-path v…

### PR DESCRIPTION
**Pull request by rbarilani**
refactor(dc-table): refactor dc-table, see #110, add $dc-image-path variable, use svg image for arrow

  BREAKING CHANGE:
```dc-table--spacious```, ```dc-table--comfortable```, etc. were removed in favor of ```dc-table__td--spacious```, ```dc-table__td--spacious```, etc.

### CODE REVIEW

**Comment by gabrielhl** [comment]
There's a few things which bother me:
1- By setting the spacing at the td level, it means more repetitive code, and also that one same table could have different spacings for each of it's tds. Flexibility x coherence. @xonic Any comments?
2 - Not all trs are necessarily clickable / interactive - so the hover effect and the arrow for mobile should be only activated when a table row is labeled as interactive, eg dc-table__tr--interactive or dc-table__tr--linked

**Comment by rbarilani** [comment]
@gabrielhl 

1. yep right it was more to try avoid nested rule since the "spacing" (padding) is applied at td level. But well maybe it make sense to use the tr level, something like ```dc-table__tr--spacious``` to allow specific rows to have more space? 

2. +1 for dc-table__tr--interactive

**Comment by rbarilani** [comment]
@gabrielhl  I force pushed the requested changes. Please check it out.
To reset your local branch t o be just like the remote.

```
git fetch origin
git checkout topic/fix-controversial-bem-table-110
git reset --hard origin/topic/fix-controversial-bem-table-110
```

**Comment by dami-gg** [comment]
I've just reviewed it and it looks fine to me. Just waiting for @gabrielhl to confirm and we can merge it.

I particularly like the new way of handling images with the path.

**Pull request merged**
