### PR TITLE
refactor(utilities): rename patterns to utilities and add examples to…

### LINKED ISSUE #178: feat(demo): add patterns page
Add patterns page under core section.

depends on #177

### PR DESCRIPTION
**Pull request by dami-gg**
… the styleguide

Closes #178

Opened this new fresh PR with the changes done in #307 since tons of conflicts were appearing there due to have committed the /dist files

### CODE REVIEW

**Comment by dami-gg** [comment]
:+1:

**Comment by gabrielhl** [comment]
In the future we'll need to update these classes and demo to make it more clear (e.g. what Island means) but for now at least it's documented.

**Comment by gabrielhl** [comment]
👍

**Comment by gregdeane** [comment]
👍

**Comment by dami-gg** [comment]
:+1:

**Pull request merged**
