### PR TITLE
feat(demo): Various demo improvements

### PR DESCRIPTION
**Pull request by gabrielhl**
- Stop menu from animating when changing pages
- Simplify menu CSS and responsive behavior
- Clean up some text in various sections
- Add color to grid demo
- Make groups look like dc-card
- Additional miscellaneous corrections & linting

### CODE REVIEW

**Comment by gregdeane** [comment]
@gabrielhl Looks like the Travis builds are failing. Please have a look.

**Comment by gabrielhl** [comment]
Something weird is going on where scss-lint is telling me to do one thing on local
image
but the exact opposite on Travis: 
image

**Comment by gabrielhl** [comment]
Reinstalling the scss_lint gem seems to fix the issue.

**Comment by sambhav-gore** [comment]
Looks good to me @gabrielhl

**Comment by sambhav-gore** [comment]
:+1:

**Comment by gabrielhl** [comment]
@sambhav-gore @gregdeane For some reason I can't merge anymore, GH isn't considering me a contributor. So can someone merge the PR and/or give me back write access to the repo.

**Pull request merged**
