### PR TITLE
Topic/search auto suggest actions

### PR DESCRIPTION
**Pull request by gabrielhl**
Replacement for #205 with additional features

### CODE REVIEW

**Comment by gabrielhl** [comment]
@sambhav-gore @gregdeane @dami-gg @cjhowald These updates should enable you to fix the issues around image sizing in search and the item action going out of the box on Safari

**Comment by gregdeane** [comment]
@gabrielhl Please merge the latest `develop` branch into this branch.

**Comment by dami-gg** [comment]
@sambhav-gore If you merge this which according to @gabrielhl fixes the problems in Safari, please verify that does not conflict with what I added to fix it on BSCS-42. From my side, if this fixes it, you can get rid of my changes in there

**Comment by sambhav-gore** [comment]
@dami-gg Tested, there seems to be no conflict.

**Pull request merged**
