### PR TITLE
topic/283-node-sass lint

### PR DESCRIPTION
**Pull request by rbarilani**
* remove "star hack" was causing problem to linter and is not needed since we don't support ie6/ie7 hopefully
* remove scss-lint in favor of sass-lint
* fix linting issue after introducing sass-lint 
* remove ruby, sass, scss-lint from development requirements (yeah nodejs all the things)

### CODE REVIEW

**Comment by rbarilani** [comment]
@gregdeane @sambhav-gore  ready to be reviewed...

**Comment by sambhav-gore** [comment]
:+1:

**Comment by cjhowald** [comment]
@rbarilani looks good to me, nice job removing the ruby + sass dependencies. One thing: please update the dev dependencies in the README.

**Comment by rbarilani** [comment]
> One thing: please update the dev dependencies in the README

@cjhowald Hi Colin, I should have already removed ruby and sass from README with this commit https://github.com/zalando/dress-code/pull/284/commits/e46209d82b384e61a2694105e28380dfc24e0f12

Do I miss something?

P.S what about the yarn.lock file?

**Comment by cjhowald** [comment]
@rbarilani oops, I missed it. You can go ahead and check in the yarn.lock file. It will provide a snapshot of all the versions and will make things easier for anyone installing via yarn.

**Comment by rbarilani** [comment]
@cjhowald Ok I'm installing yarn and update the yarn.lock file with the CLI.
Side-note: Should we maybe add YARN as a dev dependency in the README and add a section in contributing about using YARN to manage deps on top of NPM?

**Comment by cjhowald** [comment]
@rbarilani I wouldn't add yarn as a dev dependency, since it can still be installed just fine with npm. Yarn just adds some niceties (like performance, simpler commands) on top of npm. 

How did you update the yarn file? It's auto-generated, so you don't want to edit it yourself. If you pull the latest version of the branch and run `yarn` that should do it. When I do that, I see a bunch of differences.

Also, the build is now failing with a number of sass-lint errors in accordion. Can you check that out?

**Comment by rbarilani** [comment]
@cjhowald I meant mentioning YARN as a required dev dependency in the development & contributing section of the docs and istruction of what to do when you need to install/uninstall a dep (use yarn instead of npm).

... yep the linter is working ...I'll check out...

**Comment by rbarilani** [comment]
@cjhowald ok done!

**Comment by cjhowald** [comment]
👍

**Comment by cjhowald** [comment]
@rbarilani I don't think we need to address yarn in this PR. We should decide if we want to force/encourage contributors to use yarn over npm. If so, let's update the README. If not, we can leave it as is, and just update yarn.lock as needed.

**Pull request merged**
