### PR TITLE
Topic/394 accessible colors and typography

### LINKED ISSUE #394: Accessible colors & typography
Dress code color palette is not yet accessible (especially primary blue). The color palette needs to be improved, some guidance on color usage should be added and typography needs adjustment to improve readability.

### PR DESCRIPTION
**Pull request by xonic**
closes #394

### CODE REVIEW

**Comment by rbarilani** [comment]
@xonic Please update your commit messages to the "subject" doesn't start with "*"

**Comment by rbarilani** [comment]
👍

**Comment by sambhav-gore** [comment]
👍

**Comment by sh3raf** [comment]
is the #394 still open?

**Pull request merged**
