### PR TITLE
feat(tooltip): add dc--has-tooltip enhance version based on hint.css,  #157

### PR DESCRIPTION
**Pull request by rbarilani**
BREAKING CHANGE: ```dc-tooltip``` and its sub-elements were removed.
```dc-has-tooltip``` was renamed to ```dc--has-tooltip```. A positioning class must be always applied.

Replace this:
```<button class="dc-btn dc-has-tooltip" data-dc-has-tooltip="Tooltip content">Button label<button>```

With this:
```<button class="dc-btn dc--has-tooltip dc--has-tooltip-top-right" data-dc--has-tooltip="Tooltip content">Button label<button>```

@gabrielhl @xonic @dami-gg @cjhowald  based on hint.css solution, I want also add sizing modifiers as hint.css does but first I want to grab yours feedback. Thank you in advance.

### CODE REVIEW

**Comment by xonic** [comment]
I think it makes sense but I guess double dashes are not valid for HTML attributes?

**Comment by cjhowald** [comment]
The API looks good. Should I pull the branch and try it out locally, or is it not ready?

**Comment by rbarilani** [comment]
@cjhowald Is not ready yet, is under review and will be part of beta "release candidates". (the beta branch was merged into develop). Beta will introduce a good amount of breaking changes. I want to release the first 1.0.0.alpha.beta this week so you can stay updated.

reminder for semantic versioning:
1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

**Comment by rbarilani** [comment]
@xonic yep maybe is valid HTML but maybe would cause problems with js frameworks.

Example angular transforms hyphenated attributes into camel-case. The double hyphen could be a problem.

@xonic idea for the attribute?

**Comment by xonic** [comment]
I simply wouldn't use BEM for attributes. Let's relax the rules here.

**Comment by gabrielhl** [comment]
It looks fine to me. There's an additional modifier we could have which is having a tail-less tooltip that sits in the exact place of the element that has-tooltip. It's hard to explain but we have already something similar in analytics -- see this screenshot

image

**Comment by xonic** [comment]
@gabrielhl why not strive for consistency and add the little arrow in analytics?
@rbarilani looks good otherwise, I'm fine with merging.

**Pull request merged**
